Bump version in sqlx-cli README to 0.2.0
I was getting an error while running `cargo sqlx prepare` while on `sqlx` version 0.4.1:

```
error: EOF while parsing an object at line 34 column 6
```

Then I realized that I had version 0.1.0-beta.1 of sqlx-cli but 0.2.0 was released on cargo.

I upgraded to 0.2.0 and the command succeeded.

I figured that the README was mistakenly not updated with the release.